### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lloricode** [dietercoopman/mailspfchecker#2]
Hi I'm trying to create a health check using your package, but in my local seem not working using this I made https://github.com/lloricode/mailspfchecker-health-check

![Screenshot_2022-09-04_21-33-46](https://user-images.githubusercontent.com/8251344/188316277-7fef68da-573d-437c-854d-e98b974a54d4.png)

is there any missing on my set up?

**Comment by dietercoopman** [comment]
Hi, thx for reporting.  I did a little update on the package and tried your package with it and now it works for me.

Could you please check if your mailserver configured in .env is a valid server ... I think that's your problem.  I will add an extra check this week.

Have a nice day

**Comment by lloricode** [comment]
i see, thanks for the response, will take a look at it
